<#
.SYNOPSIS
  Regenerates src/Dng.Sdk/Tiff/DngTagCode.cs from
  dng_sdk_1_7_1/dng_sdk/source/dng_tag_codes.h.

  Run this after the vendored DNG SDK is upgraded to a newer spec revision.
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$headerPath = Join-Path $repoRoot 'dng_sdk_1_7_1\dng_sdk\source\dng_tag_codes.h'
$outPath = Join-Path $repoRoot 'src\Dng.Sdk\Tiff\DngTagCode.cs'

if (-not (Test-Path $headerPath)) {
    throw "Header not found: $headerPath"
}

$src = Get-Content $headerPath -Raw
$rx = '\btc([A-Za-z][A-Za-z0-9_]*)\s*=\s*(0[xX][0-9A-Fa-f]+|\d+)\s*[,}]'
$matches = [regex]::Matches($src, $rx)

$entries = foreach ($m in $matches) {
    $valRaw = $m.Groups[2].Value
    $val = if ($valRaw -match '^0[xX]') { [Convert]::ToInt64($valRaw.Substring(2), 16) } else { [int64]$valRaw }
    [PSCustomObject]@{ Name = $m.Groups[1].Value; Value = $val }
}
$buckets = $entries | Group-Object Value | Sort-Object { [int64]$_.Name }

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// <auto-generated />')
[void]$sb.AppendLine('// Generated by tools/extract-tag-codes.ps1 from')
[void]$sb.AppendLine('// dng_sdk_1_7_1/dng_sdk/source/dng_tag_codes.h.')
[void]$sb.AppendLine('// Do not edit by hand. Re-run the script after vendored-SDK upgrades.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace Dng.Sdk.Tiff;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('/// <summary>')
[void]$sb.AppendLine('/// TIFF, EXIF, and DNG-extension tag codes. Mirrors tcXxx constants in dng_tag_codes.h.')
[void]$sb.AppendLine('/// </summary>')
[void]$sb.AppendLine('[System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1028:Enum storage should be Int32", Justification = "TIFF tag IDs are uint16; the SDK uses uint to match the C++ API.")]')
[void]$sb.AppendLine('public enum DngTagCode : uint')
[void]$sb.AppendLine('{')
foreach ($b in $buckets) {
    $primary = $b.Group[0]
    $hex = '0x{0:X4}' -f [int64]$primary.Value
    [void]$sb.AppendLine("    $($primary.Name) = $hex,")
    for ($i = 1; $i -lt $b.Group.Count; $i++) {
        [void]$sb.AppendLine("    $($b.Group[$i].Name) = $($primary.Name),")
    }
}
[void]$sb.AppendLine('}')

$sb.ToString() | Set-Content -Path $outPath -Encoding UTF8
Write-Host "Wrote $($buckets.Count) tag codes ($($entries.Count) including aliases) -> $outPath"
